### ISSUE TITLE
Excuse me, where in this repo is the von Mises-Fisher distribution used?

### ISSUE THREAD

**Issue by Gary828** [deeplearning-wisc/cider#1]
" CIDER explicitly formalizes the latent representations as vMF distributions, thereby providing a direct theoretical interpretation of hyperspherical embeddings." 
I couldn't find any code related to the VMF distribution. Could you please help me with this?

**Comment by alvinmingwisc** [comment]
Thank you for your question. In CIDER, the compactness loss is simplified assuming equal concentration (kappa) per class, as shown in eq (5). The mean  (prototype) for each class is updated in an exponential-moving-average (EMA) manner (Algorithm 1 in Appendix A). The updating process does not involve sampling.

In addition, if we do not assume equal concentration, we can make kappas learnable parameters. You may refer to a related work SIREN (Algorithm 1 on page 5) for more information: https://openreview.net/pdf?id=aEFaE0W5pAd
