### ISSUE TITLE
Comparison with LogitNorm in CIFAR-10 dataset

### ISSUE THREAD

**Issue by sudarshanregmi** [deeplearning-wisc/cider#10]
Hi authors!

Thank you for your wonderful work. I was curious how CIDER's performance compares with that of LogitNorm in CIFAR-10 datasets. I did check the appendix and didn't find the desired comparison. It would be great if you could share it.

Thank you!

**Comment by alvinmingwisc** [comment]
Hi! The results of CIDER should be better than LogitNorm on CIFAR-10. We didn't have a direct comparison, but in the OpenOOD paper, they have tuned LogitNorm with ResNet-18 on CIFAR-10 and results (FPR95 / AUROC) are 

SVHN | Textures | Places365 
LogitNorm ([1], Sheet cifar10) 5.30 / 98.86  |  30.94 / 94.30 | 31.17 / 94.76
CIDER (our Table 7, for reference) 2.89/99.72 | 12.33 / 96.85 | 23.88 / 94.09 

As Logitnorm didn't implement RN18 as the backbone, if you want to use the original repo, you may replace the wrn model here to be rn18 (https://github.com/hongxin001/logitnorm_ood/tree/main/models) and train from scratch.  

[1] https://docs.google.com/spreadsheets/d/1gGHpdA3sSgfGpsrDUgt9lejvIbf5yOrDyJ511zsn1uY/edit?usp=sharing

**Comment by sudarshanregmi** [comment]
Thank you very much for the response! :D Btw, I found the desired comparison in OpenOOD V1.5. [https://docs.google.com/spreadsheets/d/1mTFrO-_STYBRcNMMEmHQrFPQzeg6S8Z2vRA8jawTwBw/edit?usp=sharing], [https://arxiv.org/pdf/2306.09301.pdf]

Hmm, if I am not wrong, they show LogitNorm to be better than CIDER in terms of AUROC in Table 1. :/ Maybe OpenOOD v1.5 didn't get some implementation details correct?

**Comment by alvinmingwisc** [comment]
From the Experiment Setup in OpenOOD v1.5, I saw that "for CIFAR-10/100 and ImageNet-200, we train a ResNet-18 [36] for 100 epochs."  It is possible CIDER does not yield better performance compared to LogitNorm if the model is only trained for 100 epochs. Typically, for contrastive learning methods, we train for 500 or more epochs on CIFAR. Similar configurations can be seen in many prior works e.g. https://github.com/HobbitLong/SupContrast/blob/master/main_supcon.py.

**Comment by sudarshanregmi** [comment]
Thanks for the response! Again, awesome work! :D
