### ISSUE TITLE
hard

### ISSUE THREAD

**Issue by jeff024** [deeplearning-wisc/cider#4]

**Comment by jeff024** [comment]
Dear authors,

Your work is very interesting, and very promising on hard-ood task of CIFAR-100 Vs CIFAR-10. According to your table 5 in your paper, you reached a fantastic result of 78.21 on CIFAR-100 (ID) Vs CIFAR-10 (OOD). However, using your provided code with default settings, I could not reproduce this result. Achieving 73.3 using momentum of 0.5 (script setting) and 68.57 using momentum of 0.95 (paper setting), also 69.10 using your pretrained checkpoints of resnet 34 on CIFAR-100. 

I'm just wondering if there is anything I've missed, such as other hyperparameter settings etc. ? 

Many thanks in advance.

**Comment by alvinmingwisc** [comment]
Are you referring to a previous version of the paper? Table 5 is the Ablation on prototype update rules. Please check the latest version of the paper in the link, where we have tuned the hyperparameters and updated the performance results with multiple seeds.

**Comment by alvinmingwisc** [comment]
I agree with you that around 70+ AUROC is not good enough for the task. My hypothesis is that the semantic ambiguity & small-scale for CIFAR-10 vs CIFAR-100 makes it challenging for methods that train from scratch without external resources (e.g., auxiliary datasets, pre-training, distillation, etc). Recent works suggest that we can achieve over 95 AUROC on this OOD task based on pre-trained networks (https://arxiv.org/abs/2106.03004, https://arxiv.org/abs/2212.12720).
